# 🚀 Fluffy CS2 Updater - Auto Build & Upload Script
# This script builds the project and uploads only loader and exe to GitHub

param(
    [string]$Version = "v1.0.40",
    [string]$Message = "Auto-update build"
)

# 📍 Paths
$ProjectPath = "C:\Users\jcdro\Downloads\CS2-Delusions-FullSource (1)\CS2 Delusions"
$UpdaterPath = "C:\Users\jcdro\Downloads\Fluffy-Cs2Updater"
$MainExePath = "$ProjectPath\bin\user\CS2 External.exe"
$LauncherPath = "$ProjectPath\bin\user\Fluffy-Launcher.exe"
$LoaderPath = "$ProjectPath\FluffyLoader\bin\Release\net6.0\win-x64\Fluffy-Cs2 Loader.exe"

Write-Host "🎮 Fluffy CS2 Updater - Build & Upload Script" -ForegroundColor Green
Write-Host "==============================================" -ForegroundColor Green

# 🏗️ Step 1: Build the project
Write-Host "📦 Building project..." -ForegroundColor Yellow
try {
    # Build main project
    $msbuildPath = "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe"
    & $msbuildPath "$ProjectPath\CS2 External.sln" /p:Configuration=Release /p:Platform=x64 /m /verbosity:minimal
    
    # Build .NET loader
    Set-Location $ProjectPath
    dotnet build FluffyLoader/FluffyLoader.csproj --configuration Release --runtime win-x64 --self-contained --verbosity minimal
    
    Write-Host "✅ Build completed successfully!" -ForegroundColor Green
}
catch {
    Write-Host "❌ Build failed: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

# 📋 Step 2: Verify files exist
Write-Host "🔍 Checking built files..." -ForegroundColor Yellow
$filesToCheck = @($MainExePath, $LauncherPath, $LoaderPath)
$missingFiles = @()

foreach ($file in $filesToCheck) {
    if (-not (Test-Path $file)) {
        $missingFiles += $file
    }
}

if ($missingFiles.Count -gt 0) {
    Write-Host "❌ Missing files: $($missingFiles -join ', ')" -ForegroundColor Red
    exit 1
}

Write-Host "✅ All files found!" -ForegroundColor Green

# 📁 Step 3: Prepare upload folder
Write-Host "📁 Preparing upload folder..." -ForegroundColor Yellow
Set-Location $UpdaterPath

# Clean previous builds
if (Test-Path "Release") {
    Remove-Item "Release" -Recurse -Force
}

# Create release folder
New-Item -ItemType Directory -Name "Release" -Force | Out-Null

# Copy only the essential files
Write-Host "📋 Copying executables..." -ForegroundColor Yellow
Copy-Item $MainExePath "Release\CS2 External.exe" -Force
Copy-Item $LauncherPath "Release\Fluffy-Launcher.exe" -Force  
Copy-Item $LoaderPath "Release\Fluffy-Cs2 Loader.exe" -Force

# Copy config files
Copy-Item "$ProjectPath\bin\user\Legit.dat" "Release\Legit.dat" -Force
Copy-Item "$ProjectPath\bin\user\Rage.dat" "Release\Rage.dat" -Force
Copy-Item "$ProjectPath\bin\user\fluffy_key.dat" "Release\fluffy_key.dat" -Force

# Copy UI assets
if (Test-Path "$ProjectPath\bin\user\Images1") {
    Copy-Item "$ProjectPath\bin\user\Images1" "Release\Images1" -Recurse -Force
}

Write-Host "✅ Files copied successfully!" -ForegroundColor Green

# 📝 Step 4: Create version info
$versionInfo = @"
# Fluffy CS2 Updater - $Version

## 📦 Build Information
- **Build Date**: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
- **Version**: $Version
- **Message**: $Message

## 🎮 Included Files
- `CS2 External.exe` - Main cheat executable
- `Fluffy-Launcher.exe` - Secure launcher
- `Fluffy-Cs2 Loader.exe` - .NET loader
- `Legit.dat` - Legit mode configuration
- `Rage.dat` - Rage mode configuration
- `fluffy_key.dat` - Authentication key
- `Images1/` - UI assets

## 🔄 Latest Offsets
Updated from CS2 Dumper repository with latest game offsets.

## 🚀 Quick Start
1. Run `Fluffy-Launcher.exe`
2. Start CS2
3. Press INSERT in-game for menu

## ⚠️ Notes
- Run as Administrator
- Disable antivirus or add exceptions
- Requires .NET 6.0 or higher
- Windows x64 only

---
**Auto-generated by build script**
"@

$versionInfo | Out-File -FilePath "Release\README.md" -Encoding UTF8

# 🚀 Step 5: Upload to GitHub
Write-Host "🚀 Uploading to GitHub..." -ForegroundColor Yellow

# Configure git if not already configured
git config user.email "9crf69djm5-creator@example.com"
git config user.name "9crf69djm5-creator"

# Add all files
git add .
git commit -m "$Message - $Version"

# Push to GitHub
try {
    git push origin master -f
    Write-Host "✅ Successfully uploaded to GitHub!" -ForegroundColor Green
}
catch {
    Write-Host "❌ Failed to upload to GitHub: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "💡 Make sure you have proper Git credentials configured" -ForegroundColor Yellow
}

# 🏷️ Step 6: Create tag
Write-Host "🏷️ Creating version tag..." -ForegroundColor Yellow
git tag -d $Version -ErrorAction SilentlyContinue
git tag $Version
git push origin $Version -f

Write-Host "🎉 Build and upload completed!" -ForegroundColor Green
Write-Host "📍 Repository: https://github.com/9crf69djm5-creator/Fluffy-Cs2Updater" -ForegroundColor Cyan
Write-Host "📦 Version: $Version" -ForegroundColor Cyan
